config/routes.rb
Rails.application.routes.draw do
  
  resources :charges, only: [:new, :create]

  resources :wikis

  devise_for :users
  
  resources :users 
  
  resources :collaborators, only: [:create, :destroy]

  root 'welcome#index'
  
  get 'about' => 'welcome#about'
  
  get "charges/downgrade" => "charges#downgrade"
  
  post "charges/downgrade" => "charges#downgrade"
  

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
    belongs_to :user
    belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis, dependent: :destroy
  has_many :collaborators
  has_many :collaborator_wikis, through: :collaborators, :source => :user
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :confirmable
  
  enum role: [:standard, :premium, :admin]
  
  after_initialize :init
  
  after_update :wikidowngrade
  
  def init
    self.role ||= 0
  end
  
  private
  
  def wikidowngrade
    return unless role_was == 'premium' && role == 'standard'
    
    wikis.each do |wiki|
      wiki.update_attribute(:private, nil) if wiki.private 
    end
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user, dependent: :destroy 
  has_many :collaborators
  has_many :collaborator_users, through: :collaborators, :source => :user 
  
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :user_id, presence: true
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include Pundit
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
 def create
   @user = User.find(current_user)
   @user.role = 'premium'
   @user.save
   
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 15_00,
     description: "Premium Membership - #{current_user.email}",
     currency: 'usd'
   )
   
   
   flash[:notice] = "You have now been updated to a Premium Account, #{current_user.email}"
   redirect_to wikis_path # or wherever
 
 
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end
 
 def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Premium Membership - #{current_user.email}",
     amount: 15_00
   }
 end
 
 def downgrade
    if current_user.premium?
       current_user.update_attribute(:role, 'standard')
       #update all wiki privacy settings associated with user id to nil 
       flash[:notice] = "You have now been downgraded to a Standard Account and your wikis will no longer be private, #{current_user.email}"
       redirect_to root_path
    else
      flash[:notice] = "You have a standard account, #{current_user.email}"
       redirect_to root_path
    end
 end
 
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by_email(params[:email])
    @collaborator = Collaborator.new(wiki: @wiki, user: @user)

    if @collaborator.save 
        flash[:notice] = "Your collaborator has been added to the wiki."
        redirect_to edit_wiki_path(@wiki)
    else
        flash[:error] = "Collaborator could not be added. Check spelling!"
        redirect_to edit_wiki_path(@wiki)
    end
  end


  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed from wiki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "Collaborator could not be removed."
      redirect_to edit_wiki_path(@wiki)
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    
   def index
     @wikis = policy_scope(Wiki)
   end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end
  
  def create
     @user = current_user
     @wiki = Wiki.new(wiki_parameters)
     @wiki.user = current_user
     authorize @wiki
     
     if @wiki.save

       flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else

       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
     end
  end
  

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  
  def update
     @wiki = Wiki.find(params[:id])
     @wiki.assign_attributes(wiki_parameters)
     authorize @wiki
 
     if @wiki.save
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :edit
     end
  end
  
  def destroy
     @wiki = Wiki.find(params[:id])
     authorize @wiki
 
     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end
  end
  
  private
    
    def wiki_parameters
        params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?
     content_tag :div, capture(&block), class: css_class
  end
    
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end      
    
    
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    
    def public_wiki?(wiki)
        ## will display on view only public wikis
        ## will check if a user is a standard, premium, or admin user or that the wiki's private value has been set to false
        
        (current_user.standard? || current_user.premium? || current_user.admin?) && (wiki.private == nil || wiki.private == false)
    end

    def private_wiki?(wiki)
        ## will display only private wikis 
        ## will check that the wiki's private value has been set to true
        
       (current_user.admin? || current_user.premium?) && wiki.private == true
    end

end

app/views/charges/edit.html.erb
<h1>Charges#edit</h1>
<p>Find me in app/views/charges/edit.html.erb</p>

app/views/charges/index.html.erb
<h1>Charges#index</h1>
<p>Find me in app/views/charges/index.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h2>Update to A Premium Account</h2>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
   <%= link_to "Click here to downgrade your account", charges_downgrade_path, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to downgrade? Your wikis will become public if you press OK.' } %>
<% end %>

app/views/charges/show.html.erb
<h1>Charges#show</h1>
<p>Find me in app/views/charges/show.html.erb</p>

app/views/collaborators/_collaborators.html.erb
<% if @wiki.user_id == current_user.id || current_user.admin? %>
  <%= form_tag collaborators_path, method: :post %>
    <%= text_field_tag :email %>
    <%= hidden_field_tag :wiki_id, @wiki.id %>
    <%= submit_tag "Add Collaborator" %>
<% end %>

</br>

<div class="container">
  <div class="row">
    <h4>Wiki Collaborators</h4>
    <% @wiki.collaborators.each do |collaborator| %>
      <p>
        <%= collaborator.user.email %>
        <% if @wiki.user_id = current_user.id || current_user.admin? %>
          <%= link_to "Delete Collaborator", [collaborator], method: :delete, class: 'btn btn-danger' %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> | 
          <%= link_to "Change Account Status", new_charge_path, :class => 'navbar-link'  %>   
    <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> 
    <% end %>

    
    <div class="container">
     <ul class="nav nav-tabs">
         <h1><%= link_to "Blocipedia", root_path %></h1>
         <h1><%= link_to "About", about_path %></h1>
         <h1><%= link_to "Wikis", wikis_path %></h1>
         
     </ul>
     
          <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>

     <%= yield %>
   </div>
   
   
    
        
    

</body>
</html>

 

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Blocipedia was created by Chirag Shah</p>

app/views/wikis/_form.html.erb
 <%= form_for [wiki] do |f| %>
   <% if wiki.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
       <ul>
         <% wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
  <% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox', as: :private do %>
      <%= f.check_box :private, {}, "true", "false" %> Private Wiki
    <% end %>
  </div>
 <% end %>
   <%= form_group_tag(wiki.errors[:title]) do %>
     <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(wiki.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
 <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>
 
 <div class="form-group">
  <%= render partial: 'collaborators/collaborators', locals: { wiki: @wiki, user: current_user } %>
 </div>

app/views/wikis/edit.html.erb
 <h1>Edit Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
       <li>If you desire, you may use Markdown. A Markdown cheat sheet can be found <%= link_to 'here', 'https://guides.github.com/features/mastering-markdown/' %>.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { wiki: @wiki } %>
   </div>
 </div>

app/views/wikis/index.html.erb
 <h1>All Public Wikis</h1>
 <% @wikis.each do |wiki| %>
 <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
       </h4>
     </div>
   </div>
 <% end %>
 
 <h1>All Private Wikis</h1>
 <% @wikis.each do |wiki| %>
 <% if private_wiki?(wiki) %>
 <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
       </h4>
     </div>
   </div>
 <% end %>
 <% end %> 

app/views/wikis/new.html.erb
<h1>New Wiki Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Wikis</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
       <li>If you desire, you may use Markdown. A Markdown cheat sheet can be found <%= link_to 'here', 'https://guides.github.com/features/mastering-markdown/' %>.</li>
     </ul>
   </div>
   <div class="col-md-8">
      <%= render partial: 'form', locals: { wiki: @wiki } %>
   </div>
 </div>

app/views/wikis/show.html.erb
 <h1><%= @wiki.title %></h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= markdown(@wiki.body) %></p>
   </div>
   <div class="col-md-4">
    <%if policy(@wiki).edit? || policy(@wiki).delete? %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <% end %>
   </div>
 </div>